--- orig_src/Makefile	2012-05-19 18:22:59.000000000 -0600
+++ Makefile	2012-05-20 09:18:39.000000000 -0600
@@ -41,9 +41,9 @@
 
 CC=gcc
 LD=gcc
-CFLAGS=-g -O2 -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wno-pointer-sign -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fno-builtin-memset -fstack-protector-all -std=gnu99 
+CFLAGS=-g -O2 -Wall -Wpointer-arith -Wuninitialized -Wsign-compare -Wformat-security -Wno-pointer-sign -fno-strict-aliasing -D_FORTIFY_SOURCE=2 -fno-builtin-memset -fstack-protector-all -std=gnu99 -I../libdlog/install/include
 CPPFLAGS=-I. -I$(srcdir) -I/home/jcook/tools/include  $(PATHS) -DHAVE_CONFIG_H
-LIBS=-lresolv -lcrypto -ldl -lutil -lz -lnsl  -lcrypt
+LIBS=-lresolv -lcrypto -ldl -lutil -lz -lnsl  -lcrypt -L../libdlog/install/lib -ldlog
 SSHLIBS=
 SSHDLIBS=
 LIBEDIT=
